### ISSUE TITLE
[Bug] Detected Ransomware Behavior?

### ISSUE THREAD

**Issue by Locked-Key** [ChrisAnd1998/FalconX-Center-Taskbar#105]
I have Bitdefender Total Security installed and it just notified me this.

![image](https://user-images.githubusercontent.com/44415788/70438606-2cc3ce80-1ac9-11ea-976c-e32f19c812f3.png)

Does FalconX have ransomware behavior integrated?

**Comment by Locked-Key** [comment]
The files that were encrypted by FalconX according to Bitdefender
![image](https://user-images.githubusercontent.com/44415788/70438741-6bf21f80-1ac9-11ea-8b65-6728b6f4d2c1.png)

**Comment by ChrisAnd1998** [comment]
Weird how it blames FalconX for encrypting files when it's clearly not doing so 😕
Also FalconX doesn't touch any file exept it's own config file.

I also did a quick scan but no AV software seem to flag FalconX
https://www.virustotal.com/gui/file/360f6640af6f14a5b84bc48e2f1d122d242bea801f7f75961e7138cc02ccdf0e/detection

Can you try to exclude the folder where you installed FalconX in?

**Comment by Locked-Key** [comment]
I understand excluding it works.

I suggest connecting with Bitdefender to file a false-positive report for FalconX to avoid future problems.

**Comment by ChrisAnd1998** [comment]
I only think it does'nt help because, as the above link bitdefender is totally fine with FalconX since i already contacted them sometime ago when they did flag FalconX as Malware. 

Something wen't wrong in their automated detection software and i don't think they can do much about that. It can basically detect anything their algoritm thinks is doing something suspisious but, idk how it linked those files you showed me.

But i will try to contact them anyway it may have a positive result.
