### ISSUE TITLE
New versions don't work on "Windows 7"

### ISSUE THREAD

**Issue by froilson** [ChrisAnd1998/FalconX-Center-Taskbar#11]
The last version that works well with Windows 7 is 24.06.2019.
The new 1.1.2 version runs but the animation when a task is removed is wrong.
The new 1.1.3, 1.1.4 versions don't start by anyway.

**Comment by user00101010** [comment]
@ChrisAnd1998 I can confirm the "animation doesn't change with options" issue Chris. Only "none" seem to be applied, everything else is one style.

Furthermore, when the computer boots up, there is an instance of FalconX visible in the Alt + Tab programs which you have to close. I have been reluctant to open separate issues for this since I'm not running the latest version, but if you prefer me to I can.

**Comment by ChrisAnd1998** [comment]
@froilson Does it work now with version 01.08.2019 ?

@user00101010 Its's better to use the latest version alot has been fixed the past few updates.

**Comment by froilson** [comment]
Hi, now with the las version, 01.08.2019 1.1.5.0 is working but the animation is not working well because when remove or add an app, the animation starts whit all the icons at the original position, close to the start button, and then animate to the center position.

**Comment by froilson** [comment]
I test the new version 25.08.2019 1.1.6.0 and the same issue is occurred I told in previous comment.

**Comment by ChrisAnd1998** [comment]
Hi froilson can you download this Pre-Release 1.1.8.0 and see if its fixed?
https://chrisandriessen.nl/web/downloads/falconx/Pre-Release/Pre-Release%201.1.8.0.zip

**Comment by froilson** [comment]
Sorry, but unfortunately I'm on holidays till October first.

When I come back I try to test your pre-release asap.

Thanks

**Comment by ChrisAnd1998** [comment]
No problem 😁,
I'll be waiting.
Have a nice holiday!

**Comment by froilson** [comment]
Hello, can't download the file, when enter the URL in browser then
redirects me to your home page.

**Comment by ChrisAnd1998** [comment]
Well i created a virtual machine with Windows 7 and the bug is still there. I am currently looking through the older builds to find out why it's happening. Thank you very much for taking the time to test it out 😁. Those fixes i tried are currently in the latest stable build but, i can confirm it doesn't work 😓. I'll keep you updated when i find a proper fix.

**Comment by ChrisAnd1998** [comment]
Sadly i can't fix this due to some differences with the taskbar in Windows 7 and 10. Making it work for Windows 7 will require me to remove the fixes i made for Windows 10. For now i will be focusing on Windows 10 until FalconX is finished. After that i may decide to make a sepperate version for Windows 7.
