### ISSUE TITLE
Small feature request.

### ISSUE THREAD

**Issue by thedovy** [ChrisAnd1998/FalconX-Center-Taskbar#117]
Hi, I really enjoy this app. Even bought it on windows store to support you! However I would like to ask for a small feature.

Maybe you could add an option to hide FalconX icon from system tray? I would really appreciate! Thank you.

![Annotation 2019-12-17 233101](https://user-images.githubusercontent.com/45642495/71035956-51e9ba00-2125-11ea-9742-4bab5c8d4756.png)

**Comment by Cabola** [comment]
But you need the icon to access the settings..

**Comment by thedovy** [comment]
> But you need the icon to access the settings..

Not really, you can have shortcut set wherever you want, for example on start menu. It's good to have options.

**Comment by ChrisAnd1998** [comment]
This may work for the normal version but, not for the store version as i can't access anything due to permissions with store apps. So i can't have 1 service and 1 gui because, you can only access the main program not multiple. It's hard to explain but, have tested it before and sadly won't let me do it like this in the store.

**Comment by ChrisAnd1998** [comment]
And i decided to do it anyway :) in update 1.3.6.0.
I found out how to add multiple applications into a single app package.
