### ISSUE TITLE
[wish] work togehter (7+ Taskbar Tweaker)

### ISSUE THREAD

**Issue by leminsc8er** [ChrisAnd1998/FalconX-Center-Taskbar#22]
> Da ich es in deutsch  leichter habe Beschreibungen präziser abzugeben werde ich mich auf meine Muttersprach zunutze machen. Bei Fragen oder Problemen einfach melden ;-)

Ich würde mich freuen, wenn Sie mit "FalconX"-Projekt und dem Autor des "[7+ Taskbar Tweaker](https://rammichael.com/7-taskbar-tweaker)" zukünftig zusammenarbeiten würden. Beide Tools sind Portable und ergänzen sich ganz gut. 
Man könnte sich ein Tray-Icon und die Optionen teilen und die Community wäre sicher sehr dankbar für die Verschmelzung. Ich habe bereits den Kontakt gesucht und warte noch auf ein Feedback.
Einige Bugs müssten jedoch behoben werden.... da bei manchen Einstellungen von "7+ Taskbar Tweaker"  die Funktion von  "FalconX"  stoppen, sodass bisher noch ein manueller Neustart von  "FalconX"  vonnöten ist.
Was halten Sie davon?

**Comment by ChrisAnd1998** [comment]
> Since I have it easier in German descriptions to give more precise I will make use of my mother tongue. Just in case of questions or problems report ;-)

> I would be glad if you would cooperate with "FalconX" project and the author of the "7+ Taskbar Tweaker" in the future. Both tools are portable and complement each other quite well.
You could share a tray icon and options and the community would be very grateful for the merger. I have already sought contact and are still waiting for feedback.
However, some bugs would have to be fixed .... because with some settings of "7+ Taskbar Tweaker" the function of "FalconX" stop, so far a manual restart of "FalconX" is needed.
What do you make of it?

Allright, thanks for letting me know. I will be fixing bugs caused between FalconX and Windows first. Then i can look at bugs caused by other third-party applications.
