### ISSUE TITLE
Multiple Monitors: Icons not centered when "main-taskbar" on second monitor.

### ISSUE THREAD

**Issue by DeruloJSON** [ChrisAnd1998/FalconX-Center-Taskbar#31]
When i have the "main-taskbar" on my second Monitor the icons on it are pushed to the right, not on the center like they should be.
The second taskbar stays fine.

This doesn´t occur when i have the "main-taskbar" on my 1st Monitor.

FalconX 1.2.5 
Windows 10 1903
![FalconXIssue](https://user-images.githubusercontent.com/56516111/66937186-50c1e100-f03f-11e9-85e4-b98150245116.png)

**Comment by ChrisAnd1998** [comment]
What happens when you click "Restart Explorer" in FalconX?

And how about this testing build?
https://chrisandriessen.nl/web/downloads/falconx/Testing/FalconX_TESTING_1.2.6.0_v4.zip

**Comment by DeruloJSON** [comment]
Both poorly didn`t change anything.

**Comment by ChrisAnd1998** [comment]
Hmm, strange. 
I also have my main screen on the second screen but i dont have this issue, even when i start changing it up. 

I will try to reproduce this bug and fix it.

**Comment by DeruloJSON** [comment]
I figured, to much information will be better than to little, so more thing i figured out when having before mentioned setup.

When using "Center between Toolbars", the icons sit to far to the left (instead of the right), but just a little bit. 
![FalconXIssueCenterBetToolbars](https://user-images.githubusercontent.com/56516111/66949733-53303500-f057-11e9-8c11-399acfba3d59.png)

Also, when setting a Custom Offset, the icons move in the other direction.
So if you put in a positive number, they will move to the left and not the right.

**Comment by v-rogg** [comment]
I can confirm the issue.
When windows display 1 is my main display the multi monitor support works with two and three monitors. When any of the other displays is my main display it doesnt work and only centers my configured main display.

**Comment by v-rogg** [comment]
So I did a bit of testing.
By disabling the animation (none and 1s) I got it to work and center perfectly on all taskbars. By enabling animations it seems like it overshoots and ends too soon.
This might not be the right issue for it, but I think it might be connected.

**Comment by ChrisAnd1998** [comment]
Thanks for testing it out :)
I am currently going through every bit of code, take the best and do a whole rewrite.

**Comment by v-rogg** [comment]
I debugged for the last few hours and read into your code.
The calculation seems to give correct results. Im currently using two monitors. When both taskbar widths change (I move a window from one screen to another) a Taskbar Calculate occurs followed by a Taskbar Update. When only my second taskbar width changes, because a programm is pinned to my main taskbar, a Taskbar Calculate occurs giving the right values but NO Taskbar Update occurs. I further looking into it.

**Comment by ChrisAnd1998** [comment]
How about this rewrite? Its very empty right now but, should do its job.
http://chrisandriessen.nl/tests/Debug.zip

**Comment by v-rogg** [comment]
Seems like it got the same problem with pinned programs. The reaction speed is a big improvement though, it changes instantly. x3 took quite some time. If you give me access to your x4 I will try to debug the pinned programs issue. Otherwise I'll try to fix it in x3, it might be transferable to x4 then.

**Comment by ChrisAnd1998** [comment]
I forgot to mention that the current build only updates when a new icon gets added. Not when the resolution, display or anything else changed. 

I was hoping it now brings you taskbars to the right positions.

Currently it's not possible to build the application because, everything is opened up now but, i will send it when its ready. The 0 position bug is just a redraw by the taskbar and can easly be fixed.

Thanks for taking the effort to fix this :)

**Comment by v-rogg** [comment]
Ah okay. When it updates it centers perfectly.
Thanks for your work with this project.

**Comment by ChrisAnd1998** [comment]
Here is a more complete version but not done yet.
https://chrisandriessen.nl/web/downloads/falconx/?dir=Testing

**Comment by v-rogg** [comment]
I just tested the new version. Im guessing you still only update when there is a new icon added.
I tested all the animations. Technically all work (besides None, but Im guessing you haven't implemented it yet) altough most overshoot (mainly INs) or undershoot (mainly OUTs) at the animation speed 100ms. For some 500ms is enough to look good others need ~1000ms. All center perfectly after the animation. This is probably a common calucaltion problem as you are stepping over or under your target.
The Transparant Taskbar works aswell.
Center between Toolbars doesnt. My main tasbar doesnt change and my second does move in the right direction, but isn't centered between the toolbars.
Besides all this I'm already loving the new version. It feels really snapy :D

**Comment by ChrisAnd1998** [comment]
Thanks for testing it so quickly :)

I indeed still have to add a none animation. And the "center between toolbars" is also broken on my side but, i will fix that. The problem with the animations is that they some times don't stop when they are on the calculated position. I have added a position check for if its not at the right position to compensate it but, i will dig deeper into that.

I am happy it finally works!

**Comment by v-rogg** [comment]
Keep up the good work!
Im really looking forward to the final version. I also like the new layout.

And the animation problem is probably because f.e. the animation steps at the rate of 1 -> 2 -> 4 -> 8 -> 16 etc. when you are at a step rate higher the missing pixels you overshoot and the animation ends after the calculated point. Same problem in the other direction. By getting a rate of 2 -> 1 -> 0.5 -> .25 you can basically never reach you goal. This problem is only visible for small animation times as the final steps are in general bigger/smaller as they would be if the animation time would be longer. Im not really sure if there is an easy way to fix this besides either looking small animation speed for certain animation types or placing a warning message that there might occur a "visual bug" if the animation time is too low.

**Comment by ChrisAnd1998** [comment]
Allright, i released version 1.2.8.0 :)
