### ISSUE TITLE
Select white/black icons independently on system theme

### ISSUE THREAD

**Issue by Martin5001** [ChrisAnd1998/FalconX-Center-Taskbar#51]
Normally when I turn system into dark mode, the taskbar icons are white and vice versa. But sometimes it would be great to be able to set icons to light/dark independently, for example if my wallpaper is mostly light but with a dark bottom part and I have transparent taskbar, then I won´t see the black icons on the black background. So I would change the icons to white but keep the light system theme.

**Comment by samwzlim** [comment]
@ChrisAnd1998 @Martin5001 Any updates on this? I wanted to open a new issue but I saw that this one already existed. Basically same issue as the one mentioned, I use the app auto dark mode automatically toggle between light and dark mode in the morning and evening, but in light mode, the start menu button, time, and other system icons will be black and in dark mode, the colors will be white instead. However, I am also using a wallpaper which is dark at the bottom, so using the acrylic style doesn't play nicely because it will make the taskbar go black, which results in this during light mode:
![x3wSArqx1Z](https://user-images.githubusercontent.com/74489037/103972783-b2242180-51a8-11eb-9960-ad330851321d.png)

Any workarounds? I really want to use acrylic style
