### ISSUE TITLE
Crash upon startup loop after explorer.exe restarted.

### ISSUE THREAD

**Issue by djsime1** [ChrisAnd1998/FalconX-Center-Taskbar#67]
Some other program caused explorer.exe to crash and restart. This caused FalconX to crash as well despite it usually not crashing with explorer. I doubt it will start again until I reboot.

Details:
- Version 1.3.0.0
- Downloaded from Microsoft Store
- Error window: https://dj.je/gvg5
- Crash detail log: https://dj.je/lyq1

Don't worry about this report too much because it's more user error than program error.

**Comment by ChrisAnd1998** [comment]
Well, FalconX should have restarted normally when the explorer.exe crashed or at least it's coded to do so. I think FalconX restared to quickly and got stuck because, the Explorer was not fully loaded yet.

To fix this i can make a check in the start-up entry of FalconX to wait for the explorer to completely load.
