### ISSUE TITLE
A little advice on software startup

### ISSUE THREAD

**Issue by fxzxmicah** [ChrisAnd1998/FalconX-Center-Taskbar#92]
First of all, I think the startup speed of the software is a little slow. Of course, this problem is not big, and the situation gap between each computer is relatively large. Secondly, when the computer starts, the interface of the software appears and disappears, I think it's not beautiful. I hope you can add a startup parameter like "/background". Double click the software to open the interface. When you start the computer, software start in the background without displaying the interface.

**Comment by ChrisAnd1998** [comment]
Will be fixed next update ;) It can be fixed very easy without the need of startup parameters.

FalconX just runs at start-up so it can take a while for it to load. Thats also why i opened a new issue myself due to some requests of other people to run FalconX at boot (before explorer.exe) but, i have not found a proper way to do so yet.

**Comment by fxzxmicah** [comment]
Run before explorer? I think it's hard.😂 I haven't seen a user level application that has a higher startup order than the system.

**Comment by Cabola** [comment]
I've just setup a manual task scheduler to run the falconx.exe "at logon of any user" as I found it to do it way faster then the programs own launch at startup. ;)

**Comment by fxzxmicah** [comment]
Nice work!!! 😄😄😄 @ChrisAnd1998 @Cabola

**Comment by ChrisAnd1998** [comment]
@fxzxmicah Thanks 😁
